apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1ERXdNVEV5TkRZME1Wb1hEVE13TVRJek1ERXlORFkwTVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTU4wCnZORWpoK2pqRjU5RGhMbXVEdVdRMGhCUVNEMW5KYzFna1M3WnF4Y1MxclZwRzJqS2IxbXh0OGwxeFY1ZkNDSlgKMmNxT2ZnTWZTaTU2aWg3MjRGODQzcXJMZTFlQ2d5MzJjcHU3ZURJV3VFcFdrWmVqR0ptK3k1Ny8yaHV1UVpkZQpSQS9COExtcWpNQ3dVTDFGZEdKeGMrWk9MU3NONnUrcmNtbXNpRXJVN3F5dlRCVUFIbUZ1elFJRlpHK0VrMlp1ClZzU2xoZDFtY2hPRHZmY0RjMDJ1MmtYNXk5WDU5eTNvWlAxR21tQk1LYWMzUkxPOXBZUGducGJZYmsyZmFOaEoKNXcwUGZBanBTbXdSR09rTkZaWjh1SUJNbFVYcWxIVjVlMFNwRWptOTMvNVNhOFRJQ0xpaWxLa3dPQXpDUFE5VQpZc25lVkhhWDJ1bWlyR1k2cDEwQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHOWJWSTRTQ1NWWnpjK0k2V3J2SWlXSjM5WVcKL0FIcWQ2QmcvZVVmWWw3djJ5ZE9qakZYbzl6UHhxOXFkWlRZQzFjWUE2cWRGSUdXaCtadCtaaG5TN1dNeVZBTApQS1pBc1JJRXhuNlIxUWc2TURYcytPU2tLMXNPVVZuSG8rVCtSWWZidTRQMmV0Ti9ZRUt6cXZGYjVHMHFacWhECmRkdG5FZGpWM2R1eVdENU5QNzZ2S1kwUlJkalVpcUxBRk1xTkxvVzJkRWcxdU5yTVJWbEhKUm10K01lSmtmcmgKVFo3STh2cjVvQTF6K0RSeTBVVitSZFVHSnFzZzRpaEtJUVRNSlQrKy8zS3hmUXNOTlBNWHZ0UXZHUVpuaEo0RQpQUHNXVklhVDdSaE9KRjdKeHUyVk5ocDdTUGRpc2RQSkxLOVBlZ1BkaGVJMERROEtVK2lCdUxGUWFQND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://B4B4921ABDA4F86EB8E0E9EC58D85E30.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:854676674973:cluster/audio-api-inference-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:854676674973:cluster/audio-api-inference-cluster
    user: arn:aws:eks:us-east-1:854676674973:cluster/audio-api-inference-cluster
  name: arn:aws:eks:us-east-1:854676674973:cluster/audio-api-inference-cluster
current-context: arn:aws:eks:us-east-1:854676674973:cluster/audio-api-inference-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:854676674973:cluster/audio-api-inference-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - audio-api-inference-cluster
      command: aws
